Models/ImagePost.cs
public class ImagePost
{
   public string Legenda { set;get; }
   public IFormFile Image { set; get; }
   public string? FilePath { get; set; }
   public string? FileName { get; set; }
}

Controllers/ImagePostController.cs
using Microsoft.AspNetCore.Mvc;

public class ImagePostController : Controller
{
    private readonly IWebHostEnvironment _hostingEnvironment;

    private static List<ImagePost> images = new List<ImagePost>();

    public ImagePostController(IWebHostEnvironment hostingEnvironment)
    {
        _hostingEnvironment = hostingEnvironment;
    }

    [HttpGet]
    public ActionResult Index()
    {
        return View(images);
    }

    [HttpGet]
    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(ImagePost model)
    {
        if (model.Image != null && model.Image.Length > 0)
        {
            model.FileName = Path.GetFileName(model.Image.FileName);
            model.FilePath = Path.Combine(_hostingEnvironment.WebRootPath, "uploads", model.FileName);

            using (var stream = new FileStream( model.FilePath!, FileMode.Create))
            {
                await model.Image.CopyToAsync(stream);
            }

            images.Add(model);

            return RedirectToAction("Index");
        }

        return BadRequest("Nenhum arquivo foi enviado.");
    }
}

Views/ImagePost/Create.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Upload</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body class="container">
    <h1>Upload de Arquivo</h1>

    <form asp-controller="ImagePost" asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="file">Selecione um arquivo:</label>
            <input type="file" id="file" name="image" class="form-control-file" />
        </div>
        <div class="form-group">
            <label for="file">Legenda:</label>
            <input type="text"  name="legenda" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</body>

</html>

Views/ImagePost/Index.cshtml
@model List<ImagePost>
<html lang="en">

<head>
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body class="container">
    

    <table class="table table-hover">
        <tr>
            <td>Legenda</td>
            <td>Imagem</td>
        </tr>

        @foreach (var image in Model)
        {
            <tr>
                <td>@image.Legenda</td>
                <td><a href="/uploads/@image.FileName">@image.FileName</a></td>
            </tr>
        }
    </table>

    <a href="/ImagePost/Create" class="btn btn-primary">Adicionar Imagem</a>
</body>

</html>